when@DevHost: &profilerBaseDev
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@DevDocker: *profilerBaseDev

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
